# Generated by Django 2.2.6 on 2019-12-04 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('is_merchant', models.BooleanField(default=False)),
                ('department', models.CharField(choices=[('Chemical Engineering', 'Chemical Engineering'), ('Biotechnology', 'Biotechnology'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Mathematics and Computing', 'Mathematics and Computing'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Design ', 'Design '), ('Biosciences and Bioengineering', 'Biosciences and Bioengineering'), ('None', 'None')], default='None', max_length=120)),
                ('club', models.CharField(choices=[('Alcheringa', 'Alcheringa'), ('Cadence', 'Cadence'), ('Anchorenza and RadioG (AnR)', 'Anchorenza and RadioG (AnR)'), ('Fine Arts', 'Fine Arts'), ('Montage', 'Montage'), ('Lumiere', 'Lumiere'), ('Octaves', 'Octaves'), ('Expressions', 'Expressions'), ('LitSoc-DebSoc', 'LitSoc-DebSoc'), ('Aeromodelling', 'Aeromodelling'), ('Astronomy', 'Astronomy'), ('Coding', 'Coding'), ('Consulting and Analytics (CnA)', 'Consulting and Analytics (CnA)'), ('Electronics ', 'Electronics '), ('Prakriti ', 'Prakriti '), ('Finance and Economics', 'Finance and Economics'), ('Robotics', 'Robotics '), ('ACUMEN', 'ACUMEN'), ('TechEvince', 'TechEvince'), ('Green Automobile', 'Green Automobile'), ('Entrepreneurial Development Cell (EDC)', 'Entrepreneurial Development Cell (EDC)'), ('Udgam', 'Udgam'), ('Techniche', 'Techniche'), ('None', 'None')], default='None', max_length=120)),
                ('batch', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('None', 'None')], default='None', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
