# Generated by Django 2.2.6 on 2020-02-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_userstripe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStripe',
        ),
    ]
