# Generated by Django 2.2.6 on 2020-03-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='club',
            field=models.CharField(choices=[('Alcher', 'Alcheringa'), ('Cadence', 'Cadence'), ('AnR', 'Anchorenza and RadioG'), ('Fine Arts', 'Fine Arts'), ('Montage', 'Montage'), ('Lumiere', 'Lumiere'), ('Octaves', 'Octaves'), ('Expressions', 'Expressions'), ('LitSoc-DebSoc', 'LitSoc-DebSoc'), ('Aeromodelling', 'Aeromodelling'), ('Astronomy', 'Astronomy'), ('Coding', 'Coding'), ('CnA', 'Consulting and Analytics'), ('Electronics', 'Electronics'), ('Prakriti', 'Prakriti'), ('FnE', 'Finance and Economics'), ('Robotics', 'Robotics '), ('ACUMEN', 'ACUMEN'), ('TechEvince', 'TechEvince'), ('Green Automobile', 'Green Automobile'), ('EDC', 'Entrepreneurial Development Cell'), ('Udgam', 'Udgam'), ('Techniche', 'Techniche'), ('None', 'None')], default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='question',
            name='department',
            field=models.CharField(choices=[('CE', 'Chemical Engineering'), ('BioTech', 'Biotechnology'), ('Civil', 'Civil Engineering'), ('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electronics and Electrical Engineering'), ('EP', 'Engineering Physics'), ('MnC', 'Mathematics and Computing'), ('Mech', 'Mechanical Engineering'), ('Design ', 'Design '), ('BnB', 'Biosciences and Bioengineering'), ('None', 'None')], default='None', max_length=120),
        ),
    ]
