# Generated by Django 2.2.6 on 2020-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200313_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
